### ISSUE TITLE
   我想付费定制下,根据这个节点请联系我

### ISSUE THREAD

**Issue by 18918951278** [bartbutenaers/node-red-contrib-msg-router#1]
thanks for your help!

**Comment by bartbutenaers** [comment]
Dear,

This node is offered as a **free** contribution for the Node-Red framework, so you don't have to pay for it!

Kind regards,
Bart

**Comment by 18918951278** [comment]
I need to customize this node specially. Please leave me a contact mailbox and give you specific requirements.
