### ISSUE TITLE
Message Router Delay Not Working for Last Output

### ISSUE THREAD

**Issue by robhix** [bartbutenaers/node-red-contrib-msg-router#6]
I am having an issue when using the delay functionality.  No matter the mode of delay, I do not receive the last message at the output.  For example, in broadcast mode with incremental delaying, setting each node to 10 ms, if I have 3 outputs, I only see messages at the first two.  If I have four outputs I only see messages at the first three.  

I have included a copy of a flow with which I am having this problem.

[{"id":"7f7754db.a3b5bc","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"aca3ac68.68dbb","type":"msg-router","z":"7f7754db.a3b5bc","routerType":"broadcast","topicDependent":false,"counterReset":false,"msgKeyField":"payload","undefinedHash":false,"outputsInfo":[{"active":true,"clone":false,"delay":"10","weight":"0"},{"active":true,"clone":false,"delay":"20","weight":"0"},{"active":true,"clone":false,"delay":"50","weight":"0"},{"active":true,"clone":false,"delay":"100","weight":"0"}],"name":"Broadcast Router","delaying":"increment_all","msgControl":false,"outputs":4,"x":810,"y":200,"wires":[["8c331775.50a358"],["7e575706.d7d4f8"],["714f28f8.995818"],["56ad5135.fb5aa"]]},{"id":"8c331775.50a358","type":"debug","z":"7f7754db.a3b5bc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":100,"wires":[]},{"id":"714f28f8.995818","type":"debug","z":"7f7754db.a3b5bc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":300,"wires":[]},{"id":"7e575706.d7d4f8","type":"debug","z":"7f7754db.a3b5bc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":200,"wires":[]},{"id":"38e1ebe2.4b7354","type":"inject","z":"7f7754db.a3b5bc","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":540,"y":200,"wires":[["aca3ac68.68dbb"]]},{"id":"56ad5135.fb5aa","type":"debug","z":"7f7754db.a3b5bc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1110,"y":380,"wires":[]}]

**Comment by bartbutenaers** [comment]
Hi @robhix,
I have created a **0.0.7** version on Github, which hopefully solves your issue.
You can install it directly from Github (in your Node-RED) folder like this:
```
npm install bartbutenaers/node-red-contrib-msg-router
```
Don't forget to refresh your browser screen to load the new version after installation!
Would be nice if you could test it and give me feedback, so I can publish it afterwards on NPM.
Bart

**Comment by robhix** [comment]
Bart,

It will be next week before I can give this a try, but I will and I will
let you know how it goes.

Rob Hix

**Comment by bartbutenaers** [comment]
Hi Rob,
This fix is published on npm in version **0.0.7** of this node.
Please reopen this issue if you have still problems with it.
Bart
